[project]
name = "diwali-sales-data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.6.0",
    "seaborn>=0.13.2",
    "nbformat>=5.10.0",
    "nbconvert>=6.5.0",
    "xgboost>=3.4.1",
    "lightgbm>=4.7.0",
]
